# Database configuration
db.host=localhost
db.port=3306
db.name=bpark
db.user=YOUR_DB_USERNAME
db.password=YOUR_DB_PASSWORD

# Email configuration
email.username=YOUR_EMAIL@gmail.com
email.password=YOUR_GMAIL_APP_PASSWORD